# Generated by Django 4.1.1 on 2022-09-28 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_abhadetails_aadhar'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='txnid',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='txnid'),
        ),
    ]
