# Generated by Django 4.1.1 on 2022-09-28 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_txnid'),
    ]

    operations = [
        migrations.AddField(
            model_name='abhadetails',
            name='refreshtoken',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Token'),
        ),
    ]
