# Generated by Django 4.1.1 on 2022-09-28 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_abhadetails_refreshtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abhadetails',
            name='refreshtoken',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Token'),
        ),
        migrations.AlterField(
            model_name='abhadetails',
            name='token',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Token'),
        ),
    ]
