# Generated by Django 4.1.1 on 2022-09-28 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_abhadetails_refreshtoken_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='abhadetails',
            old_name='aadhar',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='aadhar',
        ),
    ]
